In [ ]:
import numpy as np

points = []

for i in range(3):
    raw = input(f"Enter point {i+1} as x y z: ")
    
    coords = list(map(float, raw.split()))

    points.append(coords)

# convert list of lists to numpy array
points_array = np.array(points)

print("\nPoints array:")
print(points_array)
print("Shape:", points_array.shape)



Points array:
[[ 1.  2.  3.]
 [-1. -2. -3.]
 [ 0.  0.  0.]]
Shape: (3, 3)


In [ ]:
in_string = input("enter your desired translation as x y z")
translation = list(map(float ,in_string.split()))
in_string2 = input("enter your desired rotation as Bx By Bz")
rotation = list(map(float ,in_string2.split()))
print(translation)
print(rotation)  #m00_1685

[2.0, 3.0, 4.0]
[30.0, 60.0, 90.0]


In [9]:
import math
for i in points:
    i.append(1)
points_array = np.array(points)

translation_matrix = np.array([
    [ 1, 0, 0, translation[0]],
    [ 0, 0, 0, translation[1]],
    [ 0, 0, 1, translation[2]],
    [ 0, 0, 0, 1]
])
x_rotation_matrix =np.array([
    [1,0,0,0],
    [0,math.cos(rotation[0]),math.sin(rotation[0])*-1,0],
    [0,math.sin(rotation[0]),math.cos(rotation[0]),0],
    [0,0,0,1]
])
y_rotation_matrix =np.array([
    [math.cos(rotation[1]),0,math.sin(rotation[1]),0],
    [0,1,0,0],
    [math.sin(rotation[1])*-1,0,math.cos(rotation[1]),0],
    [0,0,0,1]
])
z_rotation_matrix =np.array([
    [math.cos(rotation[2]),math.sin(rotation[2])*-1,0,0],
    [math.sin(rotation[2]),math.cos(rotation[2]),0,0],
    [0,0,1,0],
    [0,0,0,1]
])
transformed_vectors = [translation_matrix@z_rotation_matrix@y_rotation_matrix@x_rotation_matrix@points_array[i] for i in range(3)]
print(transformed_vectors)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 8 is different from 4)